name: Linux build

on: [push, pull_request]

jobs:
  precheks:
    runs-on: ubuntu-20.04
    name: Linux -> Pre-checks

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: true # only need direct submodules

    - name: DiligentCore format validation
      working-directory: ${{github.workspace}}/DiligentCore/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_linux.sh

    - name: DiligentTools format validation
      working-directory: ${{github.workspace}}/DiligentTools/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_linux.sh

    - name: DiligentFX format validation
      working-directory: ${{github.workspace}}/DiligentFX/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_linux.sh

    - name: DiligentSamples format validation
      working-directory: ${{github.workspace}}/DiligentSamples/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_linux.sh

    - name: Codespell
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        ignore_words_list: lod
        skip: ./.git,./DiligentCore,./DiligentTools,./DiligentFX,./DiligentSamples
        path: .


  build:
    needs:   precheks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name:       ["GCC", "Clang"]
        build_type: ["Debug", "Release"]
        cmake_args: ["-DDILIGENT_BUILD_TESTS=ON"]
        include:
          - name:            "GCC"
            cmake_generator: "Unix Makefiles"
            cc:              "gcc-9"
            cxx:             "g++-9"

          - name:            "Clang"
            cmake_generator: "Ninja"
            cc:              "clang-12"
            cxx:             "clang++-12"

    name: Linux -> ${{ matrix.name }}-x64, ${{ matrix.build_type }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform:        Linux
        cmake-generator: ${{ matrix.cmake_generator }}

    - name: Configure CMake
      if:   success()
      uses: DiligentGraphics/github-action/configure-cmake@v1
      with:
        cc:         ${{ matrix.cc }}
        cxx:        ${{ matrix.cxx }}
        generator:  ${{ matrix.cmake_generator }}
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if:   success()
      uses: DiligentGraphics/github-action/build@v1

    - name: DiligentCoreTest
      if:   success()
      uses: DiligentGraphics/github-action/run-core-tests@v1

    - name: DiligentCoreAPITest VK
      if:   success()
      uses: DiligentGraphics/github-action/run-core-gpu-tests@v1
      with:
        mode: vk_sw
        args: --gtest_filter=-DrawCommandTest.DrawIndexedInstancedIndirect_FirstInstance_BaseVertex_FirstIndex_VBOffset_IBOffset_InstOffset:TextureCreation/TextureCreationTest.CreateTexture/TEX_FORMAT_BGRA8_TYPELESS

    - name: DiligentToolsTest
      if:   success()
      uses: DiligentGraphics/github-action/run-tools-tests@v1

    - name: DiligentToolsGPUTest VK
      if:   success()
      uses: DiligentGraphics/github-action/run-tools-gpu-tests@v1
      with:
        mode: vk_sw

    - name: HLSL2GLSLConverterTest
      if:   success()
      uses: DiligentGraphics/github-action/run-hlsl2glsl-converter-test@v1
